steps:

- task: MicroBuildSigningPlugin@3
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin

- task: MicroBuildSwixPlugin@3
  displayName: Install MicroBuild Swix Plugin
